### ISSUE TITLE
No output with XCode 11.1

### ISSUE THREAD

**Issue by snakeeye** [cpisciotta/xcbeautify#18]
Hi there, 

I upgraded the XCode 11.1, Unfortunately, there is no output for each file building status. 

Thanks

**Comment by thii** [comment]
Do you have an example project? I'll take a look at it later.

**Comment by snakeeye** [comment]
It could easily reproduce with any xcode project.  
1. Install XCode11.1 & command line tools. 
2. xcode-select --p make sure xcode 11 is default
3. xcrun xcodebuild xxx.xcodeproj  build | xcbeautify

There is only the final build result shows in log (success, fail). I am not able to see which file is building. 

Thanks a lot for looking into this!

**Comment by olvrlrnz** [comment]
I think it has to do with the Xcode output:
`CompileSwift normal x86_64 /tmp/test/test/AppDelegate.swift (in target 'test' from project 'test')`

because the pattern `"Compile[\w]+\s.+?\s((?:\.|[^ ])+\/((?:\.|[^ ])+\.(?:m|mm|c|cc|cpp|cxx|swift)))\s.*\(in target: (.*)\)"` expects a colon after "target". Making it optional at least shows a match on [regex101](https://regex101.com/)

Also, I don't know if `(.*)` is desirable because it puts the target and the project in the same capture group.

**Comment by thii** [comment]
Looks like Xcode changed its output format again. Would you mind to submit a PR to fix it?
