### ISSUE TITLE
Huge memory allocation with a big log file.

### ISSUE THREAD

**Issue by blastmann** [cpisciotta/xcbeautify#256]
I try to debug `xcbeatify` with a 250MB xcode build log file.

After running a moment, memory allocation is up to 1.1GB above. I think that is not a proper memory consumption.

<img width="397" alt="image" src="https://github.com/cpisciotta/xcbeautify/assets/2032369/c03dfabd-d0ce-48d7-9f2a-110122db4e06">

So I dig into the memory allocation of this situation, there is a `while-loop` in [`Xcbeatify.swift`](https://github.com/cpisciotta/xcbeautify/blob/eae9f85238c95e818ea5dabadddd07b7a60a2bf6/Sources/xcbeautify/Xcbeautify.swift#L68) without `autoreleasepool`.

Maybe we should consider to add a proper `autoreleasepool` in order to keep a low memory level like this:

<img width="401" alt="image" src="https://github.com/cpisciotta/xcbeautify/assets/2032369/3e1b55b0-e139-4db9-bea6-79300323d9d8">

**Comment by cpisciotta** [comment]
Hi @blastmann! I released two new versions of xcbeautify yesterday.

- [1.5.0](https://github.com/cpisciotta/xcbeautify/releases/tag/1.5.0) _should_ resolve your problem (also reported by #162). You can see the performance tests [here](https://github.com/cpisciotta/xcbeautify/pull/253#issue-2152869063).
- [1.6.0](https://github.com/cpisciotta/xcbeautify/releases/tag/1.6.0) introduces `SwiftCompile` support. You should see more accurate logs, since we're capturing the output; the logs should also be much faster, since we're no longer looping through each regex. You can see the performance tests [here](https://github.com/cpisciotta/xcbeautify/pull/254#issue-2153104667).

I tried your suggestion, using `autoreleasepool`, with the latest release, but I'm not seeing any significant differences in memory consumption.

This is not to say there aren't additional areas for improvement, but I think you'll notice notable improvements with the recently released versions. Let me know!

**Comment by blastmann** [comment]
Hi @cpisciotta. So glad to see there is a huge performance improvement.

I test the memory consumption with the newest code and it doesn't easy to reproduce this issue any more.

Using `autoreleasepool` in loop is some kinds of best practise of performance optimization and release memory ASAP.

Maybe we should consider using it in this situation. :)
