### ISSUE TITLE
Missing public `OutputType`

### ISSUE THREAD

**Issue by swiftyfinch** [cpisciotta/xcbeautify#270]
Hello @cpisciotta!
Firstly, I have been using xcbeautify for many years and I absolutely love it!

I noticed that you have restricted the visibility of `OutputType` from `public` to `package`.
https://github.com/swiftyfinch/Rugby/pull/366

This was important for my project as it allowed me to:
- Handle only `error`/`tests` types
- Tune messages with different types https://github.com/swiftyfinch/Rugby/pull/252
    <img width="400" src="https://github.com/swiftyfinch/Rugby/assets/64660122/22aefddc-0235-4b35-9836-ee54b0544a48">
- Output tests in a slightly different way:
    <img width="513" alt="Screenshot 2024-03-15 at 20 59 37" src="https://github.com/cpisciotta/xcbeautify/assets/64660122/4f05e782-100d-40ac-8ec6-1bfaa3f2df6c">

Could we please open it again?

**Comment by cpisciotta** [comment]
Hi @swiftyfinch. 

Thanks for being an xcbeautify user, and sorry for the delayed response!

I internalized OutputType, since I wanted this to be an implementation detail, similar to most of the other types.

In the future, my intention has been to simply read a string and output an optional (formatted) string via [Xcbeauitier](https://github.com/cpisciotta/xcbeautify/blob/main/Sources/XcbeautifyLib/XCBeautifier.swift). 

Recently, I introduced a protocol called [OutputRendering](https://github.com/cpisciotta/xcbeautify/blob/main/Sources/XcbeautifyLib/Renderers/OutputRendering.swift). Its concrete types are meant to be custom formatters, and I think that might address your use case. 

Have you looked into this, and what do you think about creating one to solve this issue?

I’d like to avoid re-exposing other types as public, since it’ll slow down some of the otherwise breaking changes I’ve been planning to make, but I’m open to other ideas.

Let me know what you think, and we can find a way to continue supporting your use case.

**Comment by swiftyfinch** [comment]
@cpisciotta I'm sorry, I'm not sure I understand what you mean.
Do you want to open `OutputRendering` protocol?

If so, it would look like this:
```swift
public protocol OutputRendering { ... }

public enum Renderer: String {
    ...

    /// Any custom render
    case custom(OutputRendering)
}

XCBeautifier(renderer: .custom(MyRender())).format(line: "something")
```

And then, any user can provide a custom render.
This is not as simple as just opening `OutputType`, but it is quite flexible.

However, there is a downside - it requires opening a lot of `*Capture` types and their properties in order to allow for custom renders. For example, `ErrorCaptureGroup`.

```swift
public protocol ErrorCaptureGroup: CaptureGroup {
    var wholeError: String { get }
}

struct MyRender: OutputRendering {
    func formatError(group: ErrorCaptureGroup) -> String {
        let errorMessage = group.wholeError
        return ... // custom implementation
    }
}
```

Did I understand you correctly?

**Comment by cpisciotta** [comment]
@swiftyfinch Not quite. I am asking if you'd be open to implementing a "Rugby-style" formatter directly in the xcbeautify project. It would obviously be consumed by Rugby, but because it'd be in the project, it could be used by others too.

**Comment by swiftyfinch** [comment]
@cpisciotta Oh, I see.
I will give it a try when I have some free time.
Thank you for the suggestion!

**Comment by cpisciotta** [comment]
@swiftyfinch No problem! Let me know how I can help.
